### ISSUE TITLE
Write something that takes in the AST, and generates some C++ and headers

### ISSUE THREAD

**Issue by mikeconley** [amccreight/ipdl_parser#16]
This will presumably be done within compiler.rs, though perhaps separate from `compile`, which looks like it's going to do the work of calling into both the parser and the generator, and I think it makes sense to be able to test those things independently (we can call `compile` if and when we want to do some end-to-end testing).

So I've been studying [lower.py](searchfox.org/mozilla-central/rev/3f614bdf91a2379a3e2c822da84e524f5e742121/ipc/ipdl/ipdl/lower.py), and I think I see what it's doing. My gut instinct, before deep-diving into it, was to do something similar from a high-level (use a Visitor to walk the AST, and accumulate a String which will be assigned to a HashMap, keyed on the path it's supposed to write the String to). It looks like there's some pre-processing that it does that I might need to study further.

Before I do this though, I recall billm talking about the difficulty of hacking on lower.py, and I don't want to just do a repeat of what lower.py and friends did without taking his experience into account. I know he wasn't impressed by the dynamic typing. Was that it, or were there more structural problems within lower.py that I should know about before potentially walking down the same path?

**Comment by mikeconley** [comment]
Care to weigh in, @bill-mccloskey, before I do this thing?

**Comment by froydnj** [comment]
One of the main problems with `lower.py` is that the intermediate AST that it's generating is *very* verbose; it almost wants to be C++, except that it's not quite general enough to be C++.  It's also just not very Pythonesque (e.g. 0 and 1 instead of `False` and `True`).  It's also not very consistent: some things take strings, others take actual objects that are really just wrappers for strings, and so forth (e.g. look at anything that gets assigned an `ExprVar` and then grep for `$THING.name`...whyyyyy).  Add in the dynamic typing, and it's just not enjoyable to try and hack on the code in any way.

I'd recommend something like the approach taken by `dom/bindings/Codegen.py`: you have objects for high-level concepts: namespaces, header includes, classes, methods on classes in various flavors, etc.  These high-level things have `declare` and `define` methods that implement the necessary behaviors.  But then the nuts and bolts of the code are largely done with strings.  Everything's still dynamically typed, so there's a bit of cargo-culting going on whenever you want to add something, but at least writing the code to do actual things is more natural.  And it's a bit more obvious where things get plugged in to particular parts of the code, rather than reading hideous AST-in-constructor functions from `lower.py`.

You don't have to understand all of `Codegen.py` to get the flavor.  Just start grepping for `CGThing` to find interesting things and skim through those.

It's also possible there's better ways to do this that take advantage of Rust.  I'm interested in @bill-mccloskey 's perspective.

**Comment by bill-mccloskey** [comment]
Thanks for looking into this Mike! I agree with Nathan: the Codegen.py approach seems much better. I do have a few additional comments.

- Please try to avoid visitors. When you can, just a match on the syntax tree. Visitors can be useful if the syntax tree is very deeply nested and you only want to process one or two kinds of nodes. But the IPDL syntax tree is pretty shallow, so I doubt they'll be needed much.

- We have a lot of problems in IPDL where something is used without being defined. This can take the form of not #including a header file or not pre-declaring a class. Cases like this are where it will be useful for the code generator to know more than just text. Maybe if you use a name that will be defined globally, you should be required to do something special so that the code generator knows about it. That way it can decide what the proper #includes and stuff are.

- IPDL has the unfortunate property that it generates everything at once. It would be nice if we could generate one .cpp/.h combination for a given IPDL input at a time. Besides sanity, it's nice to do it this way so that, when you change one IPDL file, you don't have to recompile everything that depends on any IPDL file (which is basically everything). There may be reasons why IPDL works the way it does, but I can't think of any.

- If you can, try to split things up into multiple files. If we could have separate modules for generation of send/receive code versus type serialization, that would be nice. I almost never look at the type serialization code, but the message code gets updated a lot.

**Comment by amccreight** [comment]
I started looking at this a tiny bit, just at the sub problem of generating the type defs. The type checking pass will probably have to be changed to return the IPDL types, and maybe the Decl information, which currently is only maintained internally.

**Comment by amccreight** [comment]
I'm cleaning up some old issues. I think at this point we aren't going to do "lower.rs" so I'll close this for now.
